language: node_js

node_js:
  - 5

services:
  - MongoDB

before_script:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

notifications:
  slack: andela:FzLbplkwSghKxRUKKqTyvBpd

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js