language: node_js

node_js: stable

notifications:
	slack: andela:FzLbplkwSghKxRUKKqTyvBpd

services:
  - mongodb

before_script: 
	- npm install -g gulp
	- export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0

script:
	- gulp

after_script:
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js